apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: station-warpad-masterdata-api-ha
  namespace: station-warpad-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: station-warpad-masterdata-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 150Mi
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1beta1
        kind: Ingress
        name: warpad-aks-addon-ingress-dev
      target:
        type: Value
        value: 10k