kind: Service
apiVersion: v1
metadata:
  name: station-warpad-masterdata-api-service
  namespace: station-warpad-uat
spec:
  type: ClusterIP
  #LoadBalancer
  #NodePort
  #ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: station-warpad-masterdata-api